### ISSUE TITLE
only wild rats are spawning no other rats are

### ISSUE THREAD

**Issue by madjackmatt** [Ladysnake/Rats-Mischief#107] opened 2023-04-22 12:16 UTC
olny wild and gold i spawned 1000 of them and 5 gold the rest are wild rats

**Comment by Xiribidus** [comment] 2023-04-22 12:20
You have already been told this is intended behavior, read the [wiki](https://ladysnake.org/wiki/rats-mischief#pet-rat-types) for more info about pet rat skins

**Comment by madjackmatt** [comment] 2023-04-22 12:21
no the wiki says that 1 in 150 are gold and wild rats

**Comment by madjackmatt** [comment] 2023-04-22 12:22
i have not goten any other rats in over 3k+ rats

**Comment by Xiribidus** [comment] 2023-04-22 12:23
1 in 150 rats are gold rats, the rest wild rats, that's what the wiki says

**Comment by madjackmatt** [comment] 2023-04-22 12:24
yes, but i tink its overkill i have spawn over 3000 rats and 5 where gold and the rest are wild

**Comment by Xiribidus** [comment] 2023-04-22 12:27
All rats spawning naturally are supposed to be wild rats. If you breed 2 wild rats the rat baby will have a random pet rat skin.
Golden rats are supposed to be a rare artifact, that's why they have a low chance of spawning as well.

**Comment by madjackmatt** [comment] 2023-04-22 12:28
i was useing a command block does that count as a rat spawning naturally?

**Comment by Xiribidus** [comment] 2023-04-22 12:30
Yes

**Comment by madjackmatt** [comment] 2023-04-22 12:32
ok, thank you, i will try with breeding them if that doesn't work ill open a new issue

**Comment by Pyrofab** [comment] 2023-04-22 13:34
Please do not spam issues. I am closing this one, but you can re-open it if your problem hasn't been resolved.

**Closed by Pyrofab** 2023-04-22 13:34 UTC
